### ISSUE TITLE
inconsistency

### ISSUE THREAD

**Issue by SpEcHiDe** [eljuanchosf/source-code-to-pdf#3]
In my opinion, one must not do `sudo pip install`, Instead one can do `pip install --user` !

Also, it would be great if you could have accepted the project title, description everything from the `README.md` file that are located in almost every projects.

Should I submit a PR for the same?

**Comment by eljuanchosf** [comment]
Hey! I just saw this issue, please feel free to do a PR. :)

**Comment by eljuanchosf** [comment]
Fixed in PR
